export {default as Home} from './Home/Home'
export {default as Activate} from './Activate/Activate'
export {default as Login} from './Login/Login'
export {default as ResetPassword} from './ResetPassword/ResetPassword'
export {default as ResetPasswordConfirm} from './ResetPasswordConfirm/ResetPasswordConfirm'
export {default as Signup} from './Signup/Signup'
export {default as Google} from './Google/Google'
